import { Inter, Caprasimo } from 'next/font/google';
import './globals.css';
import ConditionalHeader from './components/ConditionalHeader';
import React from 'react';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const caprasimo = Caprasimo({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-caprasimo',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

function LayoutWithHeader({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${caprasimo.variable}`}>
      <body>
        <ConditionalHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}

export default LayoutWithHeader;
