import { Inter, Caprasimo } from 'next/font/google';
import './globals.css';
import PodcasteoHeader from './components/PodcasteoHeader';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const caprasimo = Caprasimo({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-caprasimo',
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} ${caprasimo.variable}`}>
      <body>
        <PodcasteoHeader />
        <main>{children}</main>
      </body>
    </html>
  )
}
